/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacevisual;

import javax.swing.JOptionPane;

/**
 *
 * @author 1094260
 */
public class Games extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Games.class.getName());

    /**
     * Creates new form Games
     */
    public Games() {
        initComponents();
    }
    public void dados(){
        
        int escolha = 0;
        if (jrbPedra.isSelected()) {
            escolha = 0;
        }else if(jrbPapel.isSelected()){
            escolha = 1;
        }else if(jrbTesoura.isSelected()){
            escolha = 3;
        }else{
            JOptionPane.showMessageDialog(null, "Escolha uma opção");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jrbPedra = new javax.swing.JRadioButton();
        jrbPapel = new javax.swing.JRadioButton();
        jrbTesoura = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Games");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jrbPedra.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jrbPedra.setForeground(new java.awt.Color(0, 0, 0));
        jrbPedra.addActionListener(this::jrbPedraActionPerformed);
        jPanel1.add(jrbPedra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jrbPapel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jrbPapel.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jrbPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, -1));

        jrbTesoura.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jrbTesoura.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jrbTesoura, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-mão-assustadora-80.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 80, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-mão-fazendo-sinal-de-paz-80.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-mão-fazendo-sinal-de-pedra-80.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-espada-50.png"))); // NOI18N
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\1094260\\Downloads\\carregando.gif")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jrbPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPedraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPedraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Games().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbPapel;
    private javax.swing.JRadioButton jrbPedra;
    private javax.swing.JRadioButton jrbTesoura;
    // End of variables declaration//GEN-END:variables
}
